//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Api.Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با تکرار آن مطابقت ندارد.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} وارد شده تکراری می باشد.
        /// </summary>
        public static string DuplicateError {
            get {
                return ResourceManager.GetString("DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی وارد شده صحیح نمیباشد.
        /// </summary>
        public static string EmailAddressError {
            get {
                return ResourceManager.GetString("EmailAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین پست الکترونیکی پیدا نشد.
        /// </summary>
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /^(([^&lt;&gt;()[\]\\.,;:\s@\&quot;]+(\.[^&lt;&gt;()[\]\\.,;:\s@\&quot;]+)*)|(\&quot;.+\&quot;))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.
        /// </summary>
        public static string EmailRegularExp {
            get {
                return ResourceManager.GetString("EmailRegularExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاراکتر مورد نیاز {0} کاراکتر می باشد.
        /// </summary>
        public static string FixLength {
            get {
                return ResourceManager.GetString("FixLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0} به شکل صحیح وارد نمایید.
        /// </summary>
        public static string InCorrectSyntax {
            get {
                return ResourceManager.GetString("InCorrectSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر مجاز {0} می باشد.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد کاراکتر مورد نیاز {0} می باشد.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد کاراکتر مورد نیاز {0} {1} می باشد.
        /// </summary>
        public static string MinLengthWithTitle {
            get {
                return ResourceManager.GetString("MinLengthWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چنین کاربری پیدا نشد.
        /// </summary>
        public static string NotFoundPerson {
            get {
                return ResourceManager.GetString("NotFoundPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فقط عدد وارد نمایید.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /^\d+$/.
        /// </summary>
        public static string NumberRegularExp {
            get {
                return ResourceManager.GetString("NumberRegularExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده تکراری می باشد.
        /// </summary>
        public static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} وارد شده تکراری می باشد.
        /// </summary>
        public static string RemoteParam {
            get {
                return ResourceManager.GetString("RemoteParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن {0} الزامی می باشد.
        /// </summary>
        public static string Require {
            get {
                return ResourceManager.GetString("Require", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با موفقیت انجام شد.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با شکست مواجه شد .
        /// </summary>
        public static string Unsuccess {
            get {
                return ResourceManager.GetString("Unsuccess", resourceCulture);
            }
        }
    }
}
